# Builds DevU images on develop
# tagged as beta

name: Build DevU beta
on:
  push:
    branches:
      - develop

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      packages: write # to be able to publish docker image packages

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # todo run tests

      # docker image build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: build beta tagged image
        run: docker build . -t ghcr.io/${{ github.repository }}:beta

      - name: push
        run: docker push ghcr.io/${{ github.repository }}:beta
