# Builds DevU images for release
# tagged as latest and version number

name: Release
on:
  push:
    branches:
      - release

jobs:
  tag-release:
    name: tag-release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      packages: write # to be able to publish docker image packages

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: install plugins
        run: npm install @semantic-release/git @semantic-release/changelog -D

      - name: tag version number release based on commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  build-docker:
    needs:
      - tag-release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      packages: write # to be able to publish docker images

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version tag from git history
        id: tagName
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      # todo run tests

      # docker image build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: build version tagged image
        run: docker build . -t ghcr.io/${{ github.repository }}:${{ steps.tagName.outputs.tag }}

      - name: push version tagged
        run: docker push ghcr.io/${{ github.repository }}:${{ steps.tagName.outputs.tag }}

      - name: build latest tagged image
        run: docker build . -t ghcr.io/${{ github.repository }}:latest

      - name: push latest
        run: docker push ghcr.io/${{ github.repository }}:latest
